/**
 * src/lib/sitemap.ts
 * ─────────────────────────────────────────────────────────
 * Sitemap utility — classifies auto-scanned pages into groups,
 * builds the per-group sitemap XML, and builds the master sitemap
 * index. Consumed by src/pages/sitemap-*.xml.ts SSR endpoints.
 *
 * Source data: src/data/sitemap-pages.generated.ts (AUTO-GENERATED
 * by the sitemapAutoScan integration in astro.config.mjs — do not
 * edit the generated file by hand).
 *
 * To add a new group: extend `groupMeta` + add a pattern match in
 * `classify()`, then create src/pages/sitemap-<slug>.xml.ts. That's it.
 */

import { sitemapPaths } from '../data/sitemap-pages.generated';

// ── Group metadata ─────────────────────────────────────────────
// Order of keys here is the order they appear in the sitemap index.
export const groupMeta = {
  core: {
    slug:       'core',
    priority:   '1.0',
    changefreq: 'weekly',
  },
  about: {
    slug:       'about',
    priority:   '0.8',
    changefreq: 'monthly',
  },
  team: {
    slug:       'team',
    priority:   '0.8',
    changefreq: 'monthly',
  },
  services: {
    slug:       'services',
    priority:   '0.9',
    changefreq: 'weekly',
  },
  conditions: {
    slug:       'conditions',
    priority:   '0.8',
    changefreq: 'monthly',
  },
  legal: {
    slug:       'legal',
    priority:   '0.4',
    changefreq: 'yearly',
  },
  support: {
    slug:       'support',
    priority:   '0.6',
    changefreq: 'monthly',
  },
} as const;

export type GroupKey = keyof typeof groupMeta;

// Convenience object so endpoints can use `groups.services` etc.
export const groups = Object.fromEntries(
  Object.keys(groupMeta).map((k) => [k, k])
) as { [K in GroupKey]: K };

// ── Classification ─────────────────────────────────────────────
/**
 * First-match-wins path-pattern classifier. Keep the rules ordered
 * from most-specific to least-specific. Unmatched paths fall through
 * to `support` so nothing silently disappears from the sitemap.
 */
function classify(path: string): GroupKey {
  if (path === '/') return 'core';

  // Legal / policy pages
  if (
    path.startsWith('/privacy-policy')   ||
    path.startsWith('/terms-conditions') ||
    path.startsWith('/cookie-policy')    ||
    path.startsWith('/accessibility')
  ) return 'legal';

  // About / company pages
  if (
    path.startsWith('/about-us')   ||
    path.startsWith('/about')      ||
    path.startsWith('/contact')    ||
    path.startsWith('/locations')
  ) return 'about';

  // Team pages
  if (path.startsWith('/team')) return 'team';

  // Services + location-suffixed service pages (e.g. /mole-removal-newcastle/)
  if (
    path.startsWith('/services')       ||
    path.startsWith('/minor-surgery')  ||
    path.startsWith('/musculoskeletal') ||
    /-newcastle\//.test(path)          ||
    /-london\//.test(path)
  ) return 'services';

  // Conditions
  if (path.startsWith('/conditions')) return 'conditions';

  // Fallback — keeps everything discoverable
  return 'support';
}

/**
 * Group the scanned paths into a `{ groupKey: string[] }` lookup.
 * Computed once at module load (sitemapPaths is frozen at build time).
 */
function groupPaths(): Record<GroupKey, string[]> {
  const byGroup: Record<GroupKey, string[]> = {
    core:       [],
    about:      [],
    team:       [],
    services:   [],
    conditions: [],
    legal:      [],
    support:    [],
  };
  for (const p of sitemapPaths) {
    byGroup[classify(p)].push(p);
  }
  return byGroup;
}

const grouped = groupPaths();

/** Returns the list of non-empty group keys — used by the sitemap index. */
export function populatedGroups(): GroupKey[] {
  return (Object.keys(grouped) as GroupKey[]).filter((k) => grouped[k].length > 0);
}

// ── XML builders ───────────────────────────────────────────────
const HMDG_CREDIT = '<!-- Generated by HMDG | hmdg.co.uk -->';

function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Build a per-group <urlset> sitemap. Origin is picked up from
 * `Astro.url.origin` inside each SSR endpoint so localhost /
 * *.workers.dev / production domain all produce correctly-rooted URLs.
 */
export function buildSitemapXml(origin: string, group: GroupKey): string {
  const meta  = groupMeta[group];
  const paths = grouped[group];
  const today = new Date().toISOString().slice(0, 10);

  const urls = paths.map((p) => `  <url>
    <loc>${xmlEscape(origin + p)}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${meta.changefreq}</changefreq>
    <priority>${meta.priority}</priority>
  </url>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
${HMDG_CREDIT}
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

/**
 * Build the master sitemap index referencing all populated group
 * sitemaps. Skips empty groups automatically.
 */
export function buildSitemapIndexXml(origin: string): string {
  const today = new Date().toISOString().slice(0, 10);
  const entries = populatedGroups().map((g) => `  <sitemap>
    <loc>${xmlEscape(`${origin}/sitemap-${groupMeta[g].slug}.xml`)}</loc>
    <lastmod>${today}</lastmod>
  </sitemap>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
${HMDG_CREDIT}
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</sitemapindex>
`;
}
