// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import cloudflare from '@astrojs/cloudflare';
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * stripHtmlComments — tiny inline Astro integration.
 * Removes HTML comments (<!-- ... -->) from every built .html file so
 * internal notes never leak to production view-source. Preserves IE
 * conditional comments in case any third-party script relies on them.
 * Source files are untouched — only the built output is rewritten.
 *
 * Note: we deliberately do NOT defer any stylesheet here. Astro merges
 * global.css, component styles, and shared CSS into a single hashed
 * chunk under /_astro/. Deferring that chunk (e.g. via media="print"
 * onload swap) causes a flash of unstyled content because it defers
 * the entire page's styling, not just one component's. Stylesheets
 * must load synchronously to preserve correct first paint.
 */
function stripHtmlComments() {
  return {
    name: 'strip-html-comments',
    hooks: {
      'astro:build:done': (/** @type {{ dir: URL }} */ { dir }) => {
        const root = fileURLToPath(dir);
        /** @type {(d: string) => string[]} */
        const walk = (d) => {
          /** @type {string[]} */
          const out = [];
          for (const e of readdirSync(d, { withFileTypes: true })) {
            const p = join(d, e.name);
            if (e.isDirectory()) out.push(...walk(p));
            else if (p.endsWith('.html')) out.push(p);
          }
          return out;
        };
        for (const file of walk(root)) {
          const html = readFileSync(file, 'utf8');
          const cleaned = html.replace(/<!--(?!\[if)[\s\S]*?-->/g, '');
          if (cleaned !== html) writeFileSync(file, cleaned);
        }
      },
    },
  };
}

/**
 * sitemapAutoScan — Astro integration.
 * ─────────────────────────────────────────────────────────
 * Scans src/pages/ at config-setup (runs on every dev start AND
 * every production build) and writes src/data/sitemap-pages.generated.ts
 * — a simple exported array of indexable URL paths.
 *
 * Consumed by src/lib/sitemap.ts which classifies paths into groups
 * and builds XML for the SSR sitemap endpoints under src/pages/sitemap-*.xml.ts.
 *
 * Exclusion rules — a page is excluded if:
 *   - it lives under src/pages/api/            (SSR endpoints)
 *   - its file or folder name starts with `_`  (dev-only)
 *   - its URL path starts with /thank-you       (three-layer noindex)
 *   - the source contains `noindex={true}`     (opt-out prop)
 *   - it is not a .astro file                   (e.g. sitemap-*.xml.ts)
 *
 * Result: dropping a new .astro file in src/pages/ auto-adds it to
 * the sitemap on the next dev start / build. Zero manual registration.
 */
function sitemapAutoScan() {
  return {
    name: 'sitemap-auto-scan',
    hooks: {
      'astro:config:setup': (/** @type {{ config: { root: URL } }} */ { config }) => {
        const projectRoot = fileURLToPath(config.root);
        const pagesDir = join(projectRoot, 'src', 'pages');
        const dataDir  = join(projectRoot, 'src', 'data');
        const outFile  = join(dataDir, 'sitemap-pages.generated.ts');

        // Ensure src/data/ exists
        try { readdirSync(dataDir); } catch { mkdirSync(dataDir, { recursive: true }); }

        /** @type {(d: string) => string[]} */
        const walk = (d) => {
          /** @type {string[]} */
          const out = [];
          for (const e of readdirSync(d, { withFileTypes: true })) {
            if (e.name.startsWith('_')) continue;
            const p = join(d, e.name);
            if (e.isDirectory()) {
              if (e.name === 'api') continue;
              out.push(...walk(p));
            } else if (e.name.endsWith('.astro')) {
              out.push(p);
            }
          }
          return out;
        };

        /** @type {(absPath: string) => string} */
        const toUrlPath = (absPath) => {
          const rel = absPath.slice(pagesDir.length).replace(/\\/g, '/');
          let urlPath = rel.replace(/\.astro$/, '');
          if (urlPath.endsWith('/index')) urlPath = urlPath.slice(0, -'/index'.length) || '/';
          if (urlPath !== '/' && !urlPath.endsWith('/')) urlPath += '/';
          return urlPath;
        };

        /** @type {string[]} */
        const paths = [];
        for (const f of walk(pagesDir)) {
          const urlPath = toUrlPath(f);
          if (urlPath.startsWith('/thank-you')) continue;
          const src = readFileSync(f, 'utf8');
          if (/noindex\s*=\s*\{?true\}?/i.test(src)) continue;
          paths.push(urlPath);
        }
        paths.sort();

        const header = `// AUTO-GENERATED by sitemapAutoScan integration in astro.config.mjs.
// Do not edit by hand — rerun \`npm run dev\` or \`npm run build\` to refresh.
// Scanned: ${paths.length} indexable pages under src/pages/

export const sitemapPaths: readonly string[] = ${JSON.stringify(paths, null, 2)} as const;
`;
        writeFileSync(outFile, header, 'utf8');
      },
    },
  };
}

// https://astro.build/config
export default defineConfig({
  // output: 'static' is the default in Astro 6 (hybrid mode removed — same behaviour).
  // Pages opt into SSR individually with: export const prerender = false
  adapter: cloudflare({
    imageService: 'passthrough',  // Don't use Cloudflare Images binding — avoids reserved name conflict
    platformProxy: { enabled: true }, // Enable Wrangler proxy for local dev (reads .dev.vars)
  }),
  integrations: [sitemapAutoScan(), stripHtmlComments()],
  vite: {
    plugins: [tailwindcss()]
  }
});
